version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "final-python-face-rek"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-japm0ytgb3is"
s3_prefix = "final-python-face-rek"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Table=\"Faces\" Region=\"us-west-2\""
image_repositories = []
